[tools]
node = "22"
age = "latest"
direnv = "latest"
kubectl = "latest"
sops = "latest"
task = "latest"

[settings]
experimental = true

[env]
# Use the project name derived from the current directory
PROJECT_NAME = "{{ config_root | basename }}"
