apiVersion: skaffold/v2beta10
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: dxas90/learn
      docker:
        dockerfile: docker/node.dockerfile
deploy:
  helm:
    releases:
      - name: my-node-release
        namespace: learn-node
        createNamespace: true
        artifactOverrides:
          image: dxas90/learn
        chartPath: "./charts/learn"
        valuesFiles:
          - "./charts/learn/values.yaml"
